### ISSUE TITLE
Check umlaut handling / utf-8

### ISSUE THREAD

**Issue by aw-bib** [clgfr/dkfzmig#4]
For Umlauts to work correctly all stings in our dicts passed on have to be encoded in `utf-8`. They must not be unicode-Strings (`u'something`) but normal strings.

**Comment by aw-bib** [comment]
@clgfr please test this. It requires a working invenio on  at least RedHat/CentOS 6 (due to python 2.6 requirements.)

**Comment by clgfr** [comment]
seems to work fine
